version: "3"

services:
  db:
    container_name: pg
    restart: always
    image: postgres
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:    
      POSTGRES_DB: devfloydbr
      POSTGRES_USER: devfloydbr
      POSTGRES_PASSWORD: devfloydbr
    ports:
    - "5433:5432"
  db_keycloak:
    container_name: pg_keycloak
    restart: always
    image: postgres
    volumes:
      - ./.docker/postgres/keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
    - "5432:5432"
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db_keycloak
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - db_keycloak
  app:
    container_name: app
    build: ./api       
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./entrypoint.sh 
    ports:
      - 3333:3333
    volumes:
      - ./api:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db
    
